<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Date_datePickerMonthYearInput</name>
   <tag></tag>
   <elementGuidId>bb57fe83-7eae-4f30-92b5-de1bc159973c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datePickerMonthYearInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePickerMonthYearInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#datePickerMonthYearInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc6a924b-fe41-469d-87a7-de5d94486f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25de7ad9-ec4b-4503-8540-ac081caa7a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePickerMonthYearInput</value>
      <webElementGuid>2a73980f-100b-4c5a-a2ac-39dd85ee2737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>e5f270eb-64f0-48ec-8c4d-c96c3f4fb798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>06/15/2024</value>
      <webElementGuid>879e14c1-a3dc-42a0-ae90-127314e22006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePickerMonthYearInput&quot;)</value>
      <webElementGuid>9e2105c7-c4a0-41c7-851f-dc5e542b19ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePickerMonthYearInput']</value>
      <webElementGuid>b12f466e-01fa-4031-8c5f-50980f1a2ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datePickerMonthYear']/div/div/input</value>
      <webElementGuid>a40730a1-3b46-40c0-9d44-d26fdd3a7446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0810a3be-f62e-4cca-9e9b-2bd4bc5b7c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datePickerMonthYearInput']</value>
      <webElementGuid>fb52634c-33d2-457d-9ee7-67f236269982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
